services:
  - type: web
    name: xandera-backend
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        fromDatabase:
          name: xandera-postgres
          property: connectionString
      - key: FIREBASE_ADMIN_CREDENTIALS
        sync: false
      - key: FCM_SERVER_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
  - type: static_site
    name: xandera-admin
    buildCommand: npm ci && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://api.xandera-canteen.com/v1
      - key: VITE_FIREBASE_CONFIG
        sync: false

  - type: postgres
    name: xandera-postgres
    plan: starter
    databases:
      - name: xandera

cronJobs: []
